run("8-bit");
setAutoThreshold("Percentile");
//run("Threshold...");
run("Analyze Particles...", "size=500-Infinity display");
run("8-bit");
setOption("BlackBackground", false);
run("Make Binary");
run("Analyze Particles...", "size=500-Infinity display");
totalarea=getResult("Area",0);
implant=getResult("Area",1);
areamama = (41949 - totalarea);
areaofimplant = (implant/areamama);
areafinal = (areaofimplant*100);
print("area do implante (%): ", areafinal);
